# ==========================================
# SERVER CONFIGURATION
# ==========================================

server.port=${PORT:8080}

spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp


# ==========================================
# DATABASE CONFIGURATION
# Railway MySQL
# ==========================================

db.driver=com.mysql.cj.jdbc.Driver

db.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/ecommjava?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

db.username=${MYSQLUSER}

db.password=${MYSQLPASSWORD}

entitymanager.packagesToScan=com


# ==========================================
# HIBERNATE CONFIGURATION
# ==========================================

hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

hibernate.show_sql=false

hibernate.hbm2ddl.auto=update


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
